extends Node

var dishes = [

# PASTA
{
	"category": "Pasta",
	"name":"Carbonara",
	"description":"A rich, comforting pasta tossed in a creamy egg sauce with crispy, savory bacon bits.",
	"ingredients":["Pasta","Milk","Bacon","Cheese"],
	"allergens":["Gluten","Dairy"],
	"season":"All Year",
	"tier":"B",
},
{
	"category": "Pasta",
	"name":"Clam Pasta",
	"description":"Tender pasta tossed with fresh, briny clams in a light and savory garlic herb sauce.",
	"ingredients":["Pasta","Clam","Cheese"],
	"allergens":["Gluten","Shellfish","Dairy"],
	"season":"Spring",
	"tier":"B",
},
{
	"category": "Pasta",
	"name":"Tomato Beef Pasta",
	"description":"Hearty pasta smothered in a rich, tangy tomato sauce and loaded with savory minced beef.",
	"ingredients":["Pasta","Tomato","Beef","Cheese"],
	"allergens":["Gluten","Dairy"],
	"season":"Summer",
	"tier":"B",
},
{
	"category": "Pasta",
	"name":"Mushroom Chicken Pasta",
	"description":"Juicy chicken strips and earthy mushrooms served over pasta in a velvety cream sauce.",
	"ingredients":["Pasta","Mushroom","Chicken","Cheese"],
	"allergens":["Gluten","Dairy"],
	"season":"Autumn",
	"tier":"B",
},

# NOODLES
{
	"category": "Noodles",
	"name":"Classic Egg Noodle",
	"description":"Simple yet satisfying egg noodles tossed in a light, savory traditional broth.",
	"ingredients":["Wheat Noodles","Egg","Scallions"],
	"allergens":["Gluten","Eggs"],
	"season":"All Year",
	"tier":"A",
},
{
	"category": "Noodles",
	"name":"Corn Chicken Noodle",
	"description":"A comforting noodle bowl featuring sweet golden corn and tender shreds of chicken.",
	"ingredients":["Wheat Noodles","Corn","Chicken"],
	"allergens":["Gluten"],
	"season":"Summer",
	"tier":"A",
},
{
	"category": "Noodles",
	"name":"Pumpkin Tofu Noodle",
	"description":"Silky tofu and noodles served in a vibrant, naturally sweet pumpkin broth.",
	"ingredients":["Wheat Noodles","Pumpkin","Tofu","Corn"],
	"allergens":["Gluten","Soy"],
	"season":"Autumn",
	"tier":"A",
},
{
	"category": "Noodles",
	"name":"Kale Pork Ramen",
	"description":"Rich, savory ramen broth topped with tender pork slices and fresh, nutrient-rich kale.",
	"ingredients":["Ramen Noodles","Pork","Kale","Egg"],
	"allergens":["Gluten", "Eggs"],
	"season":"Winter",
	"tier":"A",
},

# SEAFOOD
{
	"category": "Seafood",
	"name":"Cherry Blossom Shrimp Rice",
	"description":"A beautiful, fragrant rice dish tossed with delicate pink shrimp and a hint of floral elegance.",
	"ingredients":["Cherry Blossom Shrimp","Scallions","Rice"],
	"allergens":["Shellfish"],
	"season":"Spring",
	"tier":"B",
},
{
	"category": "Seafood",
	"name":"Mackerel Asparagus Bowl",
	"description":"Flaky, grilled mackerel paired with crisp asparagus over a steaming bed of rice.",
	"ingredients":["Mackerel","Asparagus","Rice", "Mushroom"],
	"allergens":["Fish"],
	"season":"Spring",
	"tier":"B",
},
{
	"category": "Seafood",
	"name":"Scallop Bok Choy Bowl",
	"description":"Seared, succulent scallops served alongside tender bok choy on a bed of fluffy rice.",
	"ingredients":["Scallop","Bok Choy","Rice","Mushroom"],
	"allergens":["Shellfish"],
	"season":"Winter",
	"tier":"C",
},
{
	"category": "Seafood",
	"name":"Snow Crab Kale Stew",
	"description":"A luxurious, warming stew packed with sweet snow crab meat and hearty kale.",
	"ingredients":["Snow Crab","Kale","Corn","Rice"],
	"allergens":["Shellfish"],
	"season":"Winter",
	"tier":"C",
},

# STEAK
{
	"category": "Steaks",
	"name":"Classic Beef Plate",
	"description":"A timeless, savory dish featuring perfectly seared beef slices served with traditional sides.",
	"ingredients":["Mashed Potato","Beef","Carrot", "Garlic"],
	"allergens":["None"],
	"season":"All Year",
	"tier":"C",
},
{
	"category": "Steaks",
	"name":"Tomato Glazed Beef",
	"description":"Tender cuts of beef coated in a sweet, tangy, and vibrant tomato glaze.",
	"ingredients":["Beef","Tomato","Garlic","Mashed Potato"],
	"allergens":["None"],
	"season":"Summer",
	"tier":"C",
},
{
	"category": "Steaks",
	"name":"Truffle Mushroom Beef",
	"description":"Juicy beef paired with earthy mushrooms and elevated by a decadent drizzle of truffle oil.",
	"ingredients":["Beef","Truffle","Mushroom"],
	"allergens":["None"],
	"season":"Autumn",
	"tier":"C",
},
{
	"category": "Steaks",
	"name":"Winter Beef Stew",
	"description":"A slow-cooked, hearty stew with melt-in-your-mouth beef and root vegetables to warm the soul.",
	"ingredients":["Rice","Beef","Daikon","Kale"],
	"allergens":["None"],
	"season":"Winter",
	"tier":"B",
},

# DESSERTS
{
	"category": "Desserts",
	"name":"Classic Egg Pudding",
	"description":"A silky-smooth, traditional custard topped with a rich layer of golden caramel syrup.",
	"ingredients":["Egg","Vanilla","Milk"],
	"allergens":["Eggs","Dairy","Vanillin"],
	"season":"All Year",
	"tier":"A",
},
{
	"category": "Desserts",
	"name":"Strawberry Parfait",
	"description":"A delightful, layered treat of crisp granola, fresh strawberries, and whipped cream.",
	"ingredients":["Strawberry","Granola","Yogurt"],
	"allergens":["Dairy", "Gluten"],
	"season":"Spring",
	"tier":"A",
},
{
	"category": "Desserts",
	"name":"Peach Cream Pudding",
	"description":"A light and velvety pudding infused with the sweet, fruity essence of ripe peaches.",
	"ingredients":["Peach","Gelatin","Vanilla","Milk"],
	"allergens":["Vanillin","Dairy","Collagen"],
	"season":"Summer",
	"tier":"A",
},
{
	"category": "Desserts",
	"name":"Chestnut Cake",
	"description":"A rich, nutty sponge cake layered with sweet and decadent chestnut purée.",
	"ingredients":["Chestnut","Egg","Milk", "Chocolate"],
	"allergens":["Tree Nuts","Eggs","Dairy"],
	"season":"Autumn",
	"tier":"B",
}

]
